SELECT 
    P.PRODUCT_CODE as PRODUCT_CODE,
    SUM(O.SALES_AMOUNT * P.PRICE) as SALES
FROM PRODUCT P
    INNER JOIN OFFLINE_SALE O
    ON P.PRODUCT_ID = O.PRODUCT_ID
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC